

[package]
name = "hyper-static-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_static_server"
path = "./lib.rs"

[[bin]]
name = "example"
path = "./example.rs"




[features]

default = []




[dependencies]
hyper-simple-server = { path = "../../hyper-simple-server/sources", default-features = true }
askama = { package = "askama_patched", version = "*", default-features = true }
sass-rs = { version = "*", default-features = false }
walkdir = { version = "*", default-features = false }
rand = { version = "*", default-features = true }


[patch.crates-io]
askama_patched = { version = "*", git = "https://github.com/cipriancraciun/askama", branch = "fork/merged" }

