

[package]
name = "hyper-static-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_static_server"
path = "./lib.rs"


[features]

default = ["runtime"]

runtime = [
	"hyper-simple-server",
	"rand",
]

build = [
	"sass-alt",
	"walkdir",
]


[dependencies]
hyper-simple-server = { path = "../../hyper-simple-server/sources", default-features = true, optional = true }
rand = { version = "*", default-features = true, optional = true }
sass-alt = { version = "*", default-features = false, optional = true }
walkdir = { version = "*", default-features = false, optional = true }

