

[package]
name = "hyper-static-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_static_server"
path = "./lib.rs"


[features]

default = [
	"runtime",
	"builder",
]

runtime = [
	"hyper-simple-server",
	"rand",
]

builder = [
	"sass-rs",
	"walkdir",
	"blake2",
]


[dependencies]
hyper-simple-server = { path = "../../hyper-simple-server/sources", default-features = true, optional = true }
rand = { version = "*", default-features = true, optional = true }
sass-rs = { version = "*", default-features = false, optional = true }
walkdir = { version = "*", default-features = false, optional = true }
blake2 = { version = "*", default-features = false, features = ["std"], optional = true }

