

[package]
name = "hyper-static-server"
version = "0.1.3"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/console9/hyper-static-server"
documentation = "https://docs.rs/hyper-static-server"
description = "Simple friendly library to build static servers with hyper HTTP server."
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_static_server"
path = "./lib.rs"


[features]

default = [
	"runtime",
	"builder",
]

runtime = [
	"hyper-simple-server",
	"rand",
]

builder = [
	"sass-rs",
	"walkdir",
	"blake2",
]


[dependencies]
hyper-simple-server = { version = "0.1.1", default-features = false, features = ["hss-full"], optional = true }
rand = { version = "0.8.3", default-features = false, optional = true }
sass-rs = { version = "0.2.2", default-features = false, optional = true }
walkdir = { version = "2.3.1", default-features = false, optional = true }
blake2 = { version = "0.9.1", default-features = false, features = ["std"], optional = true }


# [patch.crates-io]
# hyper-simple-server = { path = "../../hyper-simple-server/sources" }

