
[package]
name = "hyper-static-server-example"
version = "0.0.0"
license = "MIT"
edition = "2021"
build = "./sources/build.rs"

[[bin]]
name = "example"
path = "./sources/main.rs"

[features]
default = ["server", "exporter"]
server = [
	"hyper-static-server/server",
	"hyper-static-server/runtime-sitemaps",
	"hyper-static-server/runtime-sitemaps-xml",
]
exporter = [
	"hyper-static-server/exporter",
	"hyper-static-server/runtime-sitemaps",
	"hyper-static-server/runtime-sitemaps-xml",
]

[dependencies]
hyper-static-server = { version = "0.4.0", default-features = false, features = [] }
askama = { package = "askama_patched", version = "*", default-features = true }

[build-dependencies]
hyper-static-server = { version = "0.4.0", default-features = false, features = ["builder", "builder-sass", "builder-markdown"] }

[patch.crates-io]
hyper-static-server = { path = "../../hyper-static-server/sources" }
hyper-simple-server = { path = "../../hyper-simple-server/sources" }
askama_patched = { git = "https://github.com/cipriancraciun/askama", branch = "forked/0.10.5/merged" }

