
[package]
name = "hyper-static-server-example"
version = "0.0.0"
license = "MIT"
edition = "2021"
build = "./sources/build.rs"

[[bin]]
name = "server"
path = "./sources/server.rs"
required-features = ["hyper-static-server/server"]

[[bin]]
name = "exporter"
path = "./sources/exporter.rs"
required-features = ["hyper-static-server/exporter"]

[features]
default = []

[dependencies]
hyper-static-server = { path = "../sources", default-features = false, features = ["server", "exporter"] }
askama = { package = "askama_patched", version = "*", default-features = true }

[build-dependencies]
hyper-static-server = { path = "../sources", default-features = false, features = ["builder", "builder-sass", "builder-markdown"] }

[patch.crates-io]
askama_patched = { git = "https://github.com/cipriancraciun/askama", branch = "forked/0.10.5/merged" }

