
[package]
name = "hyper-static-server-example"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
build = "./sources/build.rs"

[[bin]]
name = "example"
path = "./sources/main.rs"

[features]
default = []

[dependencies]
hyper-static-server = { path = "../sources", default-features = false, features = ["runtime"] }
askama = { package = "askama_patched", version = "*", default-features = true }

[build-dependencies]
hyper-static-server = { path = "../sources", default-features = false, features = ["builder", "builder-sass"] }

[patch.crates-io]
askama_patched = { git = "https://github.com/cipriancraciun/askama", branch = "forked/0.10.5/merged" }

