
[package]
name = "hyper-static-server-example"
version = "0.0.0"
license = "MIT"
edition = "2021"
build = "./sources/build.rs"

[[bin]]
name = "example"
path = "./sources/main.rs"

[features]
default = ["server", "exporter"]
development = [
	"hyper-static-server/builder-relaxed-dependencies",
	"hyper-static-server/builder-assets-sass-dynamic",
	"hyper-static-server/builder-markdown-dynamic",
	"hyper-static-server/builder-askama-dynamic",
]
production = [
	"hyper-static-server/production",
]
server = [
	"hyper-static-server/server",
	"hyper-static-server/runtime-macros",
	"hyper-static-server/runtime-askama",
	"hyper-static-server/runtime-askama-serde",
	"hyper-static-server/runtime-sitemaps",
	"hyper-static-server/runtime-sitemaps-xml",
]
exporter = [
	"hyper-static-server/exporter",
	"hyper-static-server/runtime-macros",
	"hyper-static-server/runtime-askama",
	"hyper-static-server/runtime-askama-serde",
	"hyper-static-server/runtime-sitemaps",
	"hyper-static-server/runtime-sitemaps-xml",
]

[dependencies]
hyper-static-server = { version = "0.4.0", default-features = false, features = [] }
# askama = { version = "0.10.5", default-features = true }
askama = { package = "askama_patched", version = "*", default-features = true }
serde = { version = "1.0.136", default-features = true }

[build-dependencies]
hyper-static-server = { version = "0.4.0", default-features = false, features = [
		"builder-macros",
		"builder-assets",
		"builder-assets-sass",
		"builder-markdown",
		"builder-askama",
		"builder-sitemaps",
	] }

[patch.crates-io]
hyper-static-server = { path = "../../hyper-static-server/sources" }
hyper-simple-server = { path = "../../hyper-simple-server/sources" }
askama_patched = { git = "https://github.com/cipriancraciun/askama", branch = "forked/0.10.5/merged" }

