

[package]
name = "hyper-static-server-example"
version = "0.0.0"
publish = false
edition = "2024"
rust-version = "1.94"
resolver = "3"
license = "MIT"

build = "./sources/build.rs"


[[bin]]
name = "example"
path = "./sources/main.rs"




[dependencies]

hyper-static-server = { version = "*", default-features = false, features = [] }

askama = { version = "*", default-features = true }

serde = { version = "*", default-features = true }


[build-dependencies]

hyper-static-server = { version = "*", default-features = false, features = ["builder-all"] }




[features]

default = [
	"server",
	"exporter",
]

development = [
	"hyper-static-server/server-all-dynamic",
	"hyper-static-server/exporter-all-dynamic",
	"hyper-static-server/builder-all-dynamic",
]

server = [
	"hyper-static-server/server-all",
]

exporter = [
	"hyper-static-server/exporter-all",
]

production = [
	"hyper-static-server/production",
]




[patch.crates-io]

# hyper-static-server = { git = "https://github.com/console9/hyper-static-server", branch = "development" }
hyper-simple-server = { git = "https://github.com/console9/hyper-simple-server", branch = "development" }
vrl-errors = { git = "https://github.com/volution/volution-rust-libraries", branch = "development" }
vrl-cli-arguments = { git = "https://github.com/volution/volution-rust-libraries", branch = "development" }

hyper-static-server = { path = "../.dependencies/hyper-static-server/sources" }
# hyper-simple-server = { path = "../.dependencies/hyper-simple-server/sources" }
# vrl-errors = { path = "../.dependencies/volution-rust-libraries/sources/errors" }
# vrl-cli-arguments = { path = "../.dependencies/volution-rust-libraries/sources/cli-arguments" }


