
[package]
name = "hyper-static-server-example"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "example"
path = "./main.rs"

[features]
default = []

[dependencies]
hyper-static-server = { path = "../sources", default-features = true }
askama = { package = "askama_patched", version = "*", default-features = true }

[patch.crates-io]
askama_patched = { version = "*", git = "https://github.com/cipriancraciun/askama", branch = "fork/merged" }

